---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: install ruby
    apt:
      name: ruby
      update_cache: yes
  - name: install ruby-dev
    apt:
      name: ruby-dev
  - name: install sass
    shell: gem install sass
  - name: download node 8.x
    shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - name: Install node
    apt: 
      name: nodejs=8.9.3-1nodesource1
      state: present
  - name: Install g++
    apt:
      name: g++
      update_cache: yes
  - name: Install brunch
    npm:
      name: brunch
      version: 2.10.12
      state: present
      global: yes
  - name: start nginx
    service:
      name: nginx
      state: restarted
  - file:
      path: /home/dev/node_modules
      state: directory
      mode: 0755
      owner: dev
      group: dev
  - name: link node_modules directory into webhost directory
    file:
      src: /home/dev/node_modules
      dest: /host-web/node_modules
      state: link
      owner: rideflow
      group: rideflow

  - name: set up node bin
    shell: 'echo "\nexport PATH=$HOME/node_modules/.bin:$PATH\n" >> /home/dev/.profile'
  - name: build javascript app
    shell: brunch build
    args:
      chdir: /host-web